#debug: true

build:
  image: firecyberice/rpi-docker:1.10.0-dev
  environment:
    - DOCKER_HOST=tcp://localhost:2375
  commands:
    - apk update && apk add git ca-certificates
    - export VERSION=$(cat VERSION)
    - export IMAGE_NAME=hypriot/rpi-swarm
    - mkdir -p /drone/src/github.com/hypriot/rpi-swarm/content/
    - mkdir -p /drone/src/github.com/docker/
    - export TIMESTAMP=$(date +"%Y-%m-%d_%H%M")
    - git clone --branch v${VERSION} https://github.com/docker/swarm /drone/src/github.com/docker/swarm
    - docker info
    - echo -e "####\nbuild swarm binary\n####"
    - docker run --rm -v /drone/:/gopath1.5/ -e DESCRIPTION="$(cat DESCRIPTION)" -e DEPENDENCIES="$(cat DEPENDENCIES)" -e VERSION -e TIMESTAMP hypriot/rpi-golang:1.5 /bin/bash -c "apt-get update && apt-get install -y mercurial && cd ${GOPATH}/src/github.com/docker/swarm && go get -v github.com/tools/godep && go get -v -d github.com/docker/swarm && go get -d -v ./... && CGO_ENABLED=0 ${GOPATH}/bin/godep go install -v -a -tags netgo -installsuffix netgo -ldflags '-extldflags \"-static\" -s' ."
    - echo -e "#####\ncreate tar and checksum\n#####"
    - cp /drone/bin/swarm /drone/src/github.com/hypriot/rpi-swarm/content/
    - chmod a+x /drone/src/github.com/hypriot/rpi-swarm/content/swarm
    - cp --parents /etc/ssl/certs/ca-certificates.crt /drone/src/github.com/hypriot/rpi-swarm/content/
    - export PACKAGE_NAME=swarm
    - export REPO=$(git rev-parse --short HEAD)
    - export BUILD_RESULTS=/drone/src/buildresult
    - export BUILD_DIR=${BUILD_RESULTS}/arm-binaries/${PACKAGE_NAME}/${TIMESTAMP}_${REPO}
    - mkdir -p ${BUILD_DIR}
    - cd /drone/src/github.com/hypriot/rpi-swarm/content/ && tar czf ${BUILD_DIR}/${PACKAGE_NAME}.tar.gz swarm etc/
    - cd ${BUILD_DIR} && shasum -a 256 ${PACKAGE_NAME}.tar.gz > ${PACKAGE_NAME}.tar.gz.sha256
    - echo -e "####\ndockerize it\n####"
    - export IMAGE_DIR=${BUILD_RESULTS}/docker-images/${PACKAGE_NAME}/${TIMESTAMP}_${REPO}
    - mkdir -p ${IMAGE_DIR}
    - export IMAGE_FILE=${IMAGE_DIR}/${PACKAGE_NAME}.tar
    - echo -e "####\ntest binary\n####"
    - echo -e "####\nbuild docker image\n####"
    - cd /drone/src/github.com/hypriot/rpi-swarm/
    - docker build -t ${IMAGE_NAME} .
    - echo -e "####\ntest docker image\n####"
    - echo -e "####\nsave docker image\n####"
    - docker save --output=${IMAGE_FILE} ${IMAGE_NAME}
    - echo -e "####\nlogin into dockerhub\n####"
    - docker login --username $$DOCKER_USER --password $$DOCKER_PASSWORD --email $$DOCKER_EMAIL
    - echo -e "####\npush image to the hub\n####"
    - docker push ${IMAGE_NAME}

compose:
  docker:
    privileged: true
    image: firecyberice/rpi-docker:1.10.0-dev-dind

publish:
  s3:
    acl: public-read
    region: $$AWS_DEFAULT_REGION
    bucket: $$AWS_BUCKET
    access_key: $$AWS_ACCESS_KEY_ID
    secret_key: $$AWS_SECRET_ACCESS_KEY
    source: /drone/src/buildresult
    target: /
    recursive: true

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: buildstatus
    username: Drone
    when:
      started: false
      success: true
      failure: true
