debug: true

build:
  image: hypriot/rpi-golang:1.5
  commands:
    - apt-get update && apt-get install -y mercurial ca-certificates
    - export VERSION=v1.0.0
    - git clone --branch v1.0.0 https://github.com/docker/swarm ${GOPATH}/src/github.com/docker/swarm
    - cd ${GOPATH}/src/github.com/docker/swarm
    - go get -v github.com/tools/godep
    - go get -v -d github.com/docker/swarm
    - go get -d -v ./...
    - CGO_ENABLED=0 ${GOPATH}/bin/godep go install -v -a -tags netgo -installsuffix netgo -ldflags '-extldflags "-static" -s' .
#
    - echo -e "#####\ncreate tar and checksum\n#####"
    - cp swarm /drone/src/github.com/hypriot/rpi-swarm/content/
    - cp --parents /etc/ssl/certs/ca-certificates.crt /drone/src/github.com/hypriot/rpi-swarm/content/
    - basename `git rev-parse --show-toplevel`
    - export PACKAGE_NAME=swarm
    - export TIMESTAMP=$(date +"%Y-%m-%d_%H%M")
    - export REPO=$(git rev-parse --short HEAD)
    - export BUILD_RESULTS=/drone/src/buildresult
    - export BUILD_DIR=${BUILD_RESULTS}/arm-binaries/{PACKAGE_NAME}/${TIMESTAMP}_${REPO}
    - mkdir -p ${BUILD_DIR}
    - cd /drone/src/github.com/hypriot/rpi-swarm/content/ && tar czf ${BUILD_DIR}/$(PACKAGE_NAME}.tar.gz swarm etc/
    - cd ${BUILD_DIR} && shasum -a 256 ${PACKAGE_NAME}.tar.gz > ${PACKAGE_NAME}.tar.gz.sha256
#
    - echo -e "#####\create deb and checksum\n#####"
    - export DESCRIPTION=$(cat DESCRIPTION)
    - export DEPENDENCIES=$(cat DEPENDENCIES)
    - mkdir -p ${BUILD_DIR}/package/${PACKAGE_NAME}/DEBIAN 
    - mkdir -p ${BUILD_DIR}/package/${PACKAGE_NAME}/usr/local/bin
    - echo -e "Package: swarm\nVersion: ${VERSION}-${BUILD_NUMBER}\nSection: admin\nPriority: optional\nArchitecture: armhf\nEssential: no\nInstalled-Size: <SIZE>\nMaintainer: blog.hypriot.com\nDescription: ${DESCRIPTION}\n${DEPENDENCIES}" > ${BUILD_DIR}/package/${PACKAGE_NAME}/DEBIAN/control
    - cat ${BUILD_DIR}/package/${PACKAGE_NAME}/DEBIAN/control
    - cp /drone/src/github.com/hypriot/rpi-swarm/content/swarm ${BUILD_DIR}/package/${PACKAGE_NAME}/usr/local/bin
    - export BINARY_SIZE=$(stat -c %s $(BUILD_DIR)/binary/$(BINARY_NAME))
    - sed 's|<SIZE>|${BINARY_SIZE}|g' -i ${BUILD_DIR}/package/${PACKAGE_NAME}/DEBIAN/control
    - cd ${BUILD_DIR}/package
    - dpkg-deb --build ${PACKAGE_NAME}
    - shasum -a 256 ${PACKAGE_NAME}.deb > ${PACKAGE_NAME}.deb.sha256
    - rm -R ${BUILD_DIR}/package/${PACKAGE_NAME}
    - cd .. && mv package/* ./ && rm -r package
    - echo -e "#####\ncreate docker image folder\n#####"
    - export IMAGE_DIR=${BUILD_RESULTS}/docker-images/{PACKAGE_NAME}/${TIMESTAMP}_${REPO}
    - mkdir -p ${IMAGE_DIR}
    - ln -s ${IMAGE_DIR} ${BUILD_RESULTS}/latest/

publish:
  docker:
#    environment:
#      - DOCKER_LAUNCH_DEBUG=true
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-registrator
    tag: 
      - v1.0.0
      - latest
    save:
      file: /drone/src/buildresultlatest/

  s3:   
    acl: public-read
    region: $$AWS_DEFAULT_REGION
    bucket: $$AWS_BUCKET
    access_key: $$AWS_ACCESS_KEY_ID
    secret_key: $$AWS_SECRET_ACCESS_KEY
    source: /drone/src/buildresult
    target: /
    recursive: true

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: buildstatus
    username: Drone
    when:
      started: false
      success: true
      failure: true

